# Generated by Django 5.1.3 on 2024-11-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_about_profile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='About User  will appear in  all products that published', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company  Name will appear in  all  products you published', max_length=255, null=True),
        ),
    ]
