# Generated by Django 5.1.3 on 2024-12-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_about_alter_profile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='Paypel Email not appear in  public profile only for  payment process if you sell product', max_length=254, null=True),
        ),
    ]
