# Generated by Django 5.1.3 on 2024-11-15 15:59

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_img1_alter_product_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.GetImageUploadTo, verbose_name='upload first image for product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.GetImageUploadTo, verbose_name='upload second image for product'),
        ),
    ]
