# Generated by Django 5.1.3 on 2024-11-15 16:08

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_img1_alter_product_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(default=1, upload_to=products.models.GetImageUploadTo, verbose_name='upload first image for product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=1, upload_to=products.models.GetImageUploadTo, verbose_name='upload second image for product'),
            preserve_default=False,
        ),
    ]
