# Generated by Django 5.1.3 on 2024-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_img1_alter_product_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default=1, help_text='summary of product description', max_length=150, verbose_name='Summary'),
            preserve_default=False,
        ),
    ]
