# Generated by Django 5.1.3 on 2024-11-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_amount_product_product_color_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Average Rating'),
        ),
    ]
