# Generated by Django 5.1.3 on 2024-11-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avg_rating',
        ),
    ]
